### ISSUE TITLE
Comment out ISDEV by default

### ISSUE THREAD

**Issue by overfl0** [TaktiCool/CLib#23]
Would it be possible to comment out #define ISDEV?

It's quite important from a CI perspective where you pull a particular commit and just build it - you don't really want the machine that does the pulling to have to change the code manually.

**Comment by jokoho48** [comment]
use the release branch there is ISDEV always disabled when we. the master should always have logging enabled because it's the current development branch.

**Comment by overfl0** [comment]
Alright, thank you, missed that one :).
