### ISSUE TITLE
Bug: getDeathAnimation doesn't return proper animation for all vehicles

### ISSUE THREAD

**Issue by Adanteh** [TaktiCool/CLib#25]
One example is the Prowler and Qiling (or whatever the name of those Apex buggies is). In the gunner for prowler you get "Unconscious" (Default return) but it's supposed to be "gunner_lsv01_kia", for driver it's also "Unconscious" where it's supposed to be "driver_lsv01_kia"

**Comment by jokoho48** [comment]
please check if it is fixed in PR #27
