### ISSUE TITLE
CLib build failed

### ISSUE THREAD

**Issue by Aebian** [TaktiCool/CLib#38]
Hi joko, any Ideas?

![alt text](https://i.imgur.com/5Ar3zk1.png "Issue")

Tried on two different machines with debian, same issue.

Regards,

Alex

**Comment by jokoho48** [comment]
hey, I just recently fixed that issue. fixed in https://github.com/TaktiCool/CLib/commit/f40ecf810560f29a4d30c39c2c87797c7083d774

**Comment by Aebian** [comment]
Thanks @jokoho48 already built clib without issues with your fix.
